# Generated by Django 5.1.4 on 2025-01-13 22:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_priority_alter_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("user", "title", "due_date")},
        ),
    ]
